import AppKit
import Foundation

nonisolated public struct SensitiveContentPolicy {
    public static let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword.concealed"),
        NSPasteboard.PasteboardType("PasswordPboardType")
    ]
    
    private static let regexes: [NSRegularExpression] = {
        let patterns = [
            // SSH Private Key
            "-----BEGIN[ A-Z0-9]*PRIVATE KEY-----",
            
            // AWS Access Key ID & Secret Access Key
            "(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|ASCA|ASIA)[A-Z0-9]{16}",
            "aws_secret_access_key\\s*[:=]\\s*[A-Za-z0-9/+=]{40}",
            
            // GitHub Token
            "(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{36,255}",
            "github_pat_[A-Za-z0-9_]{22}_[A-Za-z0-9_]{59}",
            
            // Stripe API Key
            "sk_live_[0-9a-zA-Z]{24}",
            
            // Google API Key
            "AIza[0-9A-Za-z-_]{35}",
            
            // Slack Token
            "xox[baprs]-[0-9]{10,12}-[0-9]{10,12}-[a-zA-Z0-9]{24}",
            
            // JSON Web Token (JWT)
            "eyJ[A-Za-z0-9-_=]+\\.[eyJ[A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+"
        ]
        return patterns.compactMap { try? NSRegularExpression(pattern: $0, options: [.caseInsensitive]) }
    }()
    
    /// Returns true if the pasteboard content contains sensitive data.
    public static func isSensitive(pasteboard: NSPasteboard) -> Bool {
        // 1. Check metadata types
        if let types = pasteboard.types {
            for type in sensitiveTypes {
                if types.contains(type) {
                    return true
                }
            }
        }
        
        // 2. Scan text if available
        if let text = pasteboard.string(forType: .string) {
            return isSensitive(text: text)
        }
        
        return false
    }
    
    /// Returns true if the provided text matches any of our sensitive content regex patterns.
    public static func isSensitive(text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return false }
        
        let range = NSRange(trimmed.startIndex..<trimmed.endIndex, in: trimmed)
        for regex in regexes {
            if regex.firstMatch(in: trimmed, options: [], range: range) != nil {
                return true
            }
        }
        return false
    }
}
